// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuZtO_kM0c71WjckYb45poo_fty9WnTbg',
    appId: '1:289287413829:web:4e3680f461646ca112432c',
    messagingSenderId: '289287413829',
    projectId: 'shopping-list-ac723',
    authDomain: 'shopping-list-ac723.firebaseapp.com',
    storageBucket: 'shopping-list-ac723.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPdtm9yq1xLkRivv69-rxrH__xqxlLt3U',
    appId: '1:289287413829:android:ca992ee3cdf5fc8212432c',
    messagingSenderId: '289287413829',
    projectId: 'shopping-list-ac723',
    storageBucket: 'shopping-list-ac723.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkNM0yBEMhiyQtqq44e-rMbJMcrjA1PbA',
    appId: '1:289287413829:ios:bbfefd537be280d312432c',
    messagingSenderId: '289287413829',
    projectId: 'shopping-list-ac723',
    storageBucket: 'shopping-list-ac723.appspot.com',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkNM0yBEMhiyQtqq44e-rMbJMcrjA1PbA',
    appId: '1:289287413829:ios:c44ad7c434df7b8912432c',
    messagingSenderId: '289287413829',
    projectId: 'shopping-list-ac723',
    storageBucket: 'shopping-list-ac723.appspot.com',
    iosBundleId: 'com.example.groceryApp.RunnerTests',
  );
}
